### ISSUE TITLE
Do you still use this? or is it broken?

### ISSUE THREAD

**Issue by gth001** [heston/label-commander#13]

**Comment by heston** [comment]
I use it all the time. Are you running into an issue?

**Comment by gth001** [comment]
Thanks for confirming. This sounds super useful. I gave up on getting it working earlier in the year, but my issue is probably between the keyboard and the chair. I just wanted to know it wasn't a dead end, before I sunk too many hours into learning how to use firebase. I'll give it another shot.

**Comment by heston** [comment]
Some of the dependencies are out of date, since I haven't added anything new to the project in a while. However, I can confirm that it does work!

**Comment by heston** [comment]
I just merged several updates, and have confirmed that I can get a new installation running just fine.
