### ISSUE TITLE
Wireless = Pi-Less? / SetUp Instructions

### ISSUE THREAD

**Issue by alexkere** [heston/label-commander#7]
Hi!

Because I now have one of the wireless dymo label printers I started looking for a voice assistant solution. Found yours. Looks promising.

As I do not have a Raspberry Pi (yet) I was wondering if the wireless dymo could allow a Pi-less set up. Ever thought that through? 

Anyway:  You have a bit more detailled setup instruction for Pi-newbies like me somewhere?

**Comment by heston** [comment]
This whole rig basically depends on a computer running a [CUPS](https://www.cups.org/) server. The approach would also work with a wireless printer, assuming you could get the CUPS server to print to that printer. The wireless aspect of the printer is not really relevant. What is important, is that something is listening for a request from the voice assistant, and sending it to the printer. It's unlikely the wireless printer on its own will be able to do that. It's worth noting that the host doesn't have to be a Pi. It can be any machine. The Pi is just inexpensive and can hide behind the printer.
